name: "🚀 Feature Request"
description: "Suggest a new feature or enhancement for ApplyMint AI"
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Request

        Thank you for suggesting a new feature! Please fill out the information below to help us understand your request better.

  - type: textarea
    id: problem
    attributes:
      label: Problem/Use Case
      description: "What problem are you trying to solve? What's the current limitation?"
      placeholder: "Describe the problem you're facing or the use case this feature would address..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: "How would you like this feature to work?"
      placeholder: "Describe your proposed solution or implementation..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: "Have you considered any alternative approaches?"
      placeholder: "List any alternative solutions you've considered..."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Add any other context, screenshots, or examples about the feature request here."
      placeholder: "Any additional context, mockups, or examples..."

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements Checklist
      description: "Please confirm these requirements are met:"
      options:
        - label: "This feature aligns with ApplyMint AI's mission to streamline job search using AI"
          required: true
        - label: "I've searched for existing issues and this hasn't been requested before"
          required: true
        - label: "This feature would benefit multiple users, not just a specific use case"
          required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: "How important is this feature to you?"
      options:
        - "Low - Nice to have"
        - "Medium - Would improve user experience"
        - "High - Critical for user success"
        - "Urgent - Blocks critical workflows"
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: "Your estimate of implementation complexity:"
      options:
        - "Simple - Small UI changes or basic functionality"
        - "Medium - New components or moderate backend changes"
        - "Complex - Major new features or significant architecture changes"
        - "Very Complex - Requires extensive changes across multiple systems"